<?php
/**
 * Minimal PSR-4 autoloader fallback used when the vendor/ directory
 * (generated by `composer install`) is not present.
 */

if (!defined('ABSPATH')) {
    exit;
}

spl_autoload_register(function ($class) {

    $prefix = 'WooFieldBuilder\\';

    if (strpos($class, $prefix) !== 0) {
        return;
    }

    $relative = substr($class, strlen($prefix));
    $path     = __DIR__ . '/' . str_replace('\\', '/', $relative) . '.php';

    if (file_exists($path)) {
        require $path;
    }
});
